%
% DISTRIBUTION STATEMENT A. Approved for public release. Distribution is unlimited.
%
% This material is based upon work supported by the Under Secretary of Defense for Research and Engineering under Air Force Contract No. FA8702-15-D-0001.
% Any opinions, findings, conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of
% the Under Secretary of Defense for Research and Engineering.
%
% © 2023 Massachusetts Institute of Technology.
%
% The software/firmware is provided to you on an As-Is basis
%
% Delivered to the U.S. Government with Unlimited Rights, as defined in DFARS Part 252.227-7013 or 7014 (Feb 2014).
% Notwithstanding any copyright notice, U.S. Government rights in this work are defined by DFARS 252.227-7013 or DFARS 252.227-7014 as detailed above.
% Use of this work other than as specifically authorized by the U.S. Government may violate any copyrights that exist in this work.
%

function avec = a_func(in1,in2,in3,amax,turn_loss,lse_param,softabs_param,turn_rate)
%A_FUNC
%    AVEC = A_FUNC(IN1,IN2,IN3,AMAX,TURN_LOSS,LSE_PARAM,SOFTABS_PARAM,TURN_RATE)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-Sep-2022 16:50:41

u1_prev1 = in3(1,:);
u1_prev2 = in3(2,:);
z11 = in1(1,:);
z12 = in1(2,:);
z13 = in1(3,:);
z14 = in1(4,:);
z21 = in2(1,:);
z22 = in2(2,:);
t2 = cos(z14);
t3 = sin(z14);
t4 = softabs_param.^2;
t5 = u1_prev2.^2;
t6 = z11.*2.0;
t7 = z12.*2.0;
t8 = z21.*2.0;
t9 = z22.*2.0;
t13 = (lse_param.*u1_prev1)./1.0e+1;
t10 = -t8;
t11 = -t9;
t12 = t4+t5;
t16 = exp(t13);
t14 = t6+t10;
t15 = t7+t11;
t17 = t16+1.0;
t18 = t2.*t14;
t19 = t3.*t15;
t20 = t2.*t15.*z13;
t21 = t3.*t14.*z13;
t22 = -t21;
t23 = t18+t19;
t24 = t20+t22;
avec = [t24.*turn_rate.*u1_prev2.*(-2.0e-4)-(t16.*t23.*((turn_loss.*(softabs_param-sqrt(t12)))./1.0e+2+1.0))./t17,t24.*turn_rate.*u1_prev1.*(-2.0e-4)+(1.0./sqrt(t12).*t23.*turn_loss.*u1_prev2.*log(t17))./(lse_param.*1.0e+1)];
