%
% DISTRIBUTION STATEMENT A. Approved for public release. Distribution is unlimited.
%
% This material is based upon work supported by the Under Secretary of Defense for Research and Engineering under Air Force Contract No. FA8702-15-D-0001.
% Any opinions, findings, conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of
% the Under Secretary of Defense for Research and Engineering.
%
% © 2023 Massachusetts Institute of Technology.
%
% The software/firmware is provided to you on an As-Is basis
%
% Delivered to the U.S. Government with Unlimited Rights, as defined in DFARS Part 252.227-7013 or 7014 (Feb 2014).
% Notwithstanding any copyright notice, U.S. Government rights in this work are defined by DFARS 252.227-7013 or DFARS 252.227-7014 as detailed above.
% Use of this work other than as specifically authorized by the U.S. Government may violate any copyrights that exist in this work.
%

function f1_prev = f1_prev_func(in1,in2,amax,turn_loss,lse_param,softabs_param,turn_rate)
%F1_PREV_FUNC
%    F1_PREV = F1_PREV_FUNC(IN1,IN2,AMAX,TURN_LOSS,LSE_PARAM,SOFTABS_PARAM,TURN_RATE)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-Sep-2022 16:50:43

u1_prev1 = in2(1,:);
u1_prev2 = in2(2,:);
z13 = in1(3,:);
z14 = in1(4,:);
f1_prev = [z13.*cos(z14);z13.*sin(z14);(log(exp((lse_param.*u1_prev1)./1.0e+1)+1.0).*((turn_loss.*(softabs_param-sqrt(softabs_param.^2+u1_prev2.^2)))./1.0e+2+1.0).*1.0e+1)./lse_param;(turn_rate.*u1_prev1.*u1_prev2)./5.0e+3];
