%
% DISTRIBUTION STATEMENT A. Approved for public release. Distribution is unlimited.
%
% This material is based upon work supported by the Under Secretary of Defense for Research and Engineering under Air Force Contract No. FA8702-15-D-0001.
% Any opinions, findings, conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of
% the Under Secretary of Defense for Research and Engineering.
%
% © 2023 Massachusetts Institute of Technology.
%
% The software/firmware is provided to you on an As-Is basis
%
% Delivered to the U.S. Government with Unlimited Rights, as defined in DFARS Part 252.227-7013 or 7014 (Feb 2014).
% Notwithstanding any copyright notice, U.S. Government rights in this work are defined by DFARS 252.227-7013 or DFARS 252.227-7014 as detailed above.
% Use of this work other than as specifically authorized by the U.S. Government may violate any copyrights that exist in this work.
%

function psi1 = psi1_func(in1,in2,delta,R)
%PSI1_FUNC
%    PSI1 = PSI1_FUNC(IN1,IN2,DELTA,R)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-Sep-2022 16:50:44

z11 = in1(1,:);
z12 = in1(2,:);
z13 = in1(3,:);
z14 = in1(4,:);
z21 = in2(1,:);
z22 = in2(2,:);
z23 = in2(3,:);
z24 = in2(4,:);
t2 = z11.*2.0;
t3 = z12.*2.0;
t4 = z21.*2.0;
t5 = z22.*2.0;
t6 = -t4;
t7 = -t5;
t8 = t2+t6;
t9 = t3+t7;
psi1 = -delta.*((z11-z21).^2+(z12-z22).^2-R.^2)-t8.*z13.*cos(z14)+t8.*z23.*cos(z24)-t9.*z13.*sin(z14)+t9.*z23.*sin(z24);
